name: Build SVT-AV1 Windows

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Builder Repo
        uses: actions/checkout@v4

      - name: Clone Official SVT-AV1 Source
        run: git clone "https://github.com" svt-av1-source

      - name: Build SVT-AV1
        uses: Akatmks/build-svt-av1@v2
        with:
          path: "./svt-av1-source"
          static: "true"
          shared: "false"
          pgo-video: "SolLevante"
          pgo-parameters: "--crf 20 --tune 0"

      - name: Upload Windows App Binary
        uses: actions/upload-artifact@v4
        with:
          name: SVT-AV1-Windows-Binary
          path: svt-av1-source/BuildAction/**/static/SvtAv1EncApp.exe
          if-no-files-found: error
